name: "Python Code Style, Quality, and Lint"
description: "Supports a plethora of tools for checking your Python code and packages"
inputs:
  python-root-list:
    description: "A list of all paths to test"
    required: false
    default: "."
  use-black:
    description: "Use Black"
    required: false
    default: false
  use-yapf:
    description: "Use yapf"
    required: false
    default: false
  use-isort:
    description: "Use isort"
    required: false
    default: true
  use-docformatter:
    description: "Use docformatter"
    required: false
    default: true
  use-pycodestyle:
    description: "Use pycodestyle"
    required: false
    default: true
  use-pydocstyle:
    description: "Use pydocstyle"
    required: false
    default: true
  use-mypy:
    description: "Use mypy"
    required: false
    default: true
  use-pylint:
    description: "Use Pylint"
    required: false
    default: true
  use-flake8:
    description: "Use Flake8"
    required: false
    default: true
  use-mccabe:
    description: "Use mccabe"
    required: false
    default: false
  use-radon:
    description: "Use radon"
    required: false
    default: false
  use-rstcheck:
    description: "Use rstcheck"
    required: false
    default: true
  use-check-manifest:
    description: "Use check-manifest"
    required: false
    default: true
  use-pyroma:
    description: "Use pyroma"
    required: false
    default: true
  extra-black-options:
    description: "Extra options: black --check $(extra-black-options) $(python-root-list)"
    required: false
    default: ""
  extra-yapf-options:
    description: "Extra options: yapf $(extra-yapf-optsion) $(python-root-list)"
    required: false
    default: ""
  extra-isort-options:
    description: "Extra options: isort -rc $(extra-isort-options) $(python-root-list) -c --diff "
    required: false
    default: ""
  extra-docformatter-options:
    description: "Extra options: docformatter $(extra-docformatter-options) $(python-root-list)"
    required: false
    default: ""
  extra-pycodestyle-options:
    description: "Extra options: pycodestyle $(extra-pycodestyle-options) $(python-root-list)"
    required: false
    default: ""
  extra-pydocstyle-options:
    description: "Extra options: pydocstyle $(extra-pydocstyle-options) $(python-root-list)"
    required: false
    default: ""
  extra-mypy-options:
    description: "Extra options: mypy $(extra-mypy-options) $(python-root-list)"
    required: false
    default: ""
  extra-pylint-options:
    description: "Extra options: pylint $(extra-pylint-options) $(python-root-list)"
    required: false
    default: ""
  extra-flake8-options:
    description: "Extra options: flake8 $(extra-flake8-options) $(python-root-list)"
    required: false
    default: ""
  extra-mccabe-options:
    description: "Extra options: python -m mccabe $(extra-mccabe-options) $(python-root-list)"
    required: false
    default: ""
  extra-radon-options:
    description: "Extra options: radon $(extra-radon-options) $(python-root-list)"
    required: false
    default: ""
  extra-rstcheck-options:
    description: "Extra options: rstcheck $(extra-rstcheck-options) $(python-root-list)"
    required: false
    default: ""
  extra-manifest-options:
    description: "Extra options: check-manifest $(extra-manifest-options) ."
    required: false
    default: ""
  extra-pyroma-options:
    description: "Extra options: pyroma $(extra-manifest-options) ."
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.python-root-list }}
    - ${{ inputs.use-black }}
    - ${{ inputs.use-yapf }}
    - ${{ inputs.use-isort }}
    - ${{ inputs.use-docformatter }}
    - ${{ inputs.use-pycodestyle }}
    - ${{ inputs.use-pydocstyle }}
    - ${{ inputs.use-mypy }}
    - ${{ inputs.use-pylint }}
    - ${{ inputs.use-flake8 }}
    - ${{ inputs.use-mccabe }}
    - ${{ inputs.use-radon }}
    - ${{ inputs.use-rstcheck }}
    - ${{ inputs.use-check-manifest }}
    - ${{ inputs.use-pyroma }}
    - ${{ inputs.extra-black-options }}
    - ${{ inputs.extra-yapf-options }}
    - ${{ inputs.extra-isort-options }}
    - ${{ inputs.extra-docformatter-options }}
    - ${{ inputs.extra-pycodestyle-options }}
    - ${{ inputs.extra-pydocstyle-options }}
    - ${{ inputs.extra-mypy-options }}
    - ${{ inputs.extra-pylint-options }}
    - ${{ inputs.extra-flake8-options }}
    - ${{ inputs.extra-mccabe-options }}
    - ${{ inputs.extra-radon-options }}
    - ${{ inputs.extra-rstcheck-options }}
    - ${{ inputs.extra-manifest-options }}
    - ${{ inputs.extra-pyroma-options }}
branding:
  icon: "terminal"
  color: "white"
